import type { Song, Artist, Album } from "@/types";
import { createSilentAudioUrl } from "@/utils/audio";

const mockArtists: Record<string, Artist> = {
  a1: {
    id: "a1",
    name: "Luna Wavefield",
    imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=300&h=300&fit=crop",
    genres: ["Electronic", "Ambient"],
    followers: 284_000,
    popularity: 72,
    topTracks: [],
    albums: [],
    bio: "Electronic musician known for atmospheric soundscapes.",
  },
  a2: {
    id: "a2",
    name: "The Rustics",
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop",
    genres: ["Indie Folk", "Acoustic"],
    followers: 156_000,
    popularity: 65,
    topTracks: [],
    albums: [],
    bio: "Indie folk duo from Portland.",
  },
  a3: {
    id: "a3",
    name: "Neon Pulse",
    imageUrl: "https://images.unsplash.com/photo-1524650359799-842906ca1c06?w=300&h=300&fit=crop",
    genres: ["Synthwave", "Retro"],
    followers: 412_000,
    popularity: 81,
    topTracks: [],
    albums: [],
    bio: "Synthwave producer bringing back the 80s.",
  },
  a4: {
    id: "a4",
    name: "Jade Horizon",
    imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&h=300&fit=crop",
    genres: ["Jazz", "Lo-Fi"],
    followers: 198_000,
    popularity: 68,
    topTracks: [],
    albums: [],
    bio: "Lo-fi jazz beats for relaxation.",
  },
  a5: {
    id: "a5",
    name: "Cascade",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&h=300&fit=crop",
    genres: ["Post-Rock", "Instrumental"],
    followers: 93_000,
    popularity: 55,
    topTracks: [],
    albums: [],
    bio: "Instrumental post-rock band.",
  },
};

const mockAlbums: Record<string, Album> = {
  al1: {
    id: "al1",
    title: "Midnight Frequencies",
    artists: [mockArtists.a1!],
    coverUrl: "https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=300&h=300&fit=crop",
    releaseDate: "2025-03-15",
    totalTracks: 4,
    genres: ["Electronic", "Ambient"],
    label: "Wavefield Records",
    copyrights: [],
    songs: [],
    popularity: 74,
  },
  al2: {
    id: "al2",
    title: "Timber & Vine",
    artists: [mockArtists.a2!],
    coverUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=300&h=300&fit=crop",
    releaseDate: "2024-11-01",
    totalTracks: 4,
    genres: ["Indie Folk", "Acoustic"],
    label: "Rustic Records",
    copyrights: [],
    songs: [],
    popularity: 67,
  },
  al3: {
    id: "al3",
    title: "Neon Dreams",
    artists: [mockArtists.a3!],
    coverUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=300&h=300&fit=crop",
    releaseDate: "2025-06-20",
    totalTracks: 4,
    genres: ["Synthwave", "Retro"],
    label: "Pulse Records",
    copyrights: [],
    songs: [],
    popularity: 83,
  },
  al4: {
    id: "al4",
    title: "Quiet Corner",
    artists: [mockArtists.a4!],
    coverUrl: "https://images.unsplash.com/photo-1518602164578-cd0074062767?w=300&h=300&fit=crop",
    releaseDate: "2025-01-10",
    totalTracks: 4,
    genres: ["Jazz", "Lo-Fi"],
    label: "Horizon Records",
    copyrights: [],
    songs: [],
    popularity: 70,
  },
  al5: {
    id: "al5",
    title: "Drift",
    artists: [mockArtists.a5!],
    coverUrl: "https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=300&h=300&fit=crop",
    releaseDate: "2024-09-05",
    totalTracks: 4,
    genres: ["Post-Rock", "Instrumental"],
    label: "Cascade Music",
    copyrights: [],
    songs: [],
    popularity: 58,
  },
};

const silentUrl = createSilentAudioUrl();

export const MOCK_TRACKS: Song[] = [
  {
    id: "t1",
    title: "Starlight Drift",
    artists: [mockArtists.a1!],
    album: mockAlbums.al1!,
    duration: 204,
    trackNumber: 1,
    discNumber: 1,
    genres: ["Electronic", "Ambient"],
    releaseDate: "2025-03-15",
    coverUrl: mockAlbums.al1!.coverUrl,
    audioUrl: silentUrl,
    popularity: 80,
  },
  {
    id: "t2",
    title: "Echoes in Mono",
    artists: [mockArtists.a1!],
    album: mockAlbums.al1!,
    duration: 178,
    trackNumber: 2,
    discNumber: 1,
    genres: ["Electronic", "Ambient"],
    releaseDate: "2025-03-15",
    coverUrl: mockAlbums.al1!.coverUrl,
    audioUrl: silentUrl,
    popularity: 72,
  },
  {
    id: "t3",
    title: "Pulse Wave",
    artists: [mockArtists.a1!],
    album: mockAlbums.al1!,
    duration: 245,
    trackNumber: 3,
    discNumber: 1,
    genres: ["Electronic"],
    releaseDate: "2025-03-15",
    coverUrl: mockAlbums.al1!.coverUrl,
    audioUrl: silentUrl,
    popularity: 65,
  },
  {
    id: "t4",
    title: "Nightfall Sequence",
    artists: [mockArtists.a1!],
    album: mockAlbums.al1!,
    duration: 312,
    trackNumber: 4,
    discNumber: 1,
    genres: ["Ambient"],
    releaseDate: "2025-03-15",
    coverUrl: mockAlbums.al1!.coverUrl,
    audioUrl: silentUrl,
    popularity: 88,
  },
  {
    id: "t5",
    title: "Campfire Song",
    artists: [mockArtists.a2!],
    album: mockAlbums.al2!,
    duration: 196,
    trackNumber: 1,
    discNumber: 1,
    genres: ["Indie Folk"],
    releaseDate: "2024-11-01",
    coverUrl: mockAlbums.al2!.coverUrl,
    audioUrl: silentUrl,
    popularity: 70,
  },
  {
    id: "t6",
    title: "Hollow Road",
    artists: [mockArtists.a2!],
    album: mockAlbums.al2!,
    duration: 223,
    trackNumber: 2,
    discNumber: 1,
    genres: ["Indie Folk", "Acoustic"],
    releaseDate: "2024-11-01",
    coverUrl: mockAlbums.al2!.coverUrl,
    audioUrl: silentUrl,
    popularity: 62,
  },
  {
    id: "t7",
    title: "Golden Hour",
    artists: [mockArtists.a2!],
    album: mockAlbums.al2!,
    duration: 167,
    trackNumber: 3,
    discNumber: 1,
    genres: ["Acoustic"],
    releaseDate: "2024-11-01",
    coverUrl: mockAlbums.al2!.coverUrl,
    audioUrl: silentUrl,
    popularity: 75,
  },
  {
    id: "t8",
    title: "Fireside",
    artists: [mockArtists.a2!],
    album: mockAlbums.al2!,
    duration: 280,
    trackNumber: 4,
    discNumber: 1,
    genres: ["Indie Folk"],
    releaseDate: "2024-11-01",
    coverUrl: mockAlbums.al2!.coverUrl,
    audioUrl: silentUrl,
    popularity: 58,
  },
  {
    id: "t9",
    title: "Retrograde",
    artists: [mockArtists.a3!],
    album: mockAlbums.al3!,
    duration: 234,
    trackNumber: 1,
    discNumber: 1,
    genres: ["Synthwave"],
    releaseDate: "2025-06-20",
    coverUrl: mockAlbums.al3!.coverUrl,
    audioUrl: silentUrl,
    popularity: 85,
  },
  {
    id: "t10",
    title: "Chrome Sunset",
    artists: [mockArtists.a3!],
    album: mockAlbums.al3!,
    duration: 198,
    trackNumber: 2,
    discNumber: 1,
    genres: ["Synthwave", "Retro"],
    releaseDate: "2025-06-20",
    coverUrl: mockAlbums.al3!.coverUrl,
    audioUrl: silentUrl,
    popularity: 79,
  },
  {
    id: "t11",
    title: "Digital Rain",
    artists: [mockArtists.a3!],
    album: mockAlbums.al3!,
    duration: 267,
    trackNumber: 3,
    discNumber: 1,
    genres: ["Synthwave"],
    releaseDate: "2025-06-20",
    coverUrl: mockAlbums.al3!.coverUrl,
    audioUrl: silentUrl,
    popularity: 82,
  },
  {
    id: "t12",
    title: "Neon Lights",
    artists: [mockArtists.a3!],
    album: mockAlbums.al3!,
    duration: 189,
    trackNumber: 4,
    discNumber: 1,
    genres: ["Retro"],
    releaseDate: "2025-06-20",
    coverUrl: mockAlbums.al3!.coverUrl,
    audioUrl: silentUrl,
    popularity: 73,
  },
  {
    id: "t13",
    title: "Rainy Window",
    artists: [mockArtists.a4!],
    album: mockAlbums.al4!,
    duration: 156,
    trackNumber: 1,
    discNumber: 1,
    genres: ["Lo-Fi"],
    releaseDate: "2025-01-10",
    coverUrl: mockAlbums.al4!.coverUrl,
    audioUrl: silentUrl,
    popularity: 69,
  },
  {
    id: "t14",
    title: "Warm Mug",
    artists: [mockArtists.a4!],
    album: mockAlbums.al4!,
    duration: 142,
    trackNumber: 2,
    discNumber: 1,
    genres: ["Jazz", "Lo-Fi"],
    releaseDate: "2025-01-10",
    coverUrl: mockAlbums.al4!.coverUrl,
    audioUrl: silentUrl,
    popularity: 64,
  },
  {
    id: "t15",
    title: "Dusk Melody",
    artists: [mockArtists.a4!],
    album: mockAlbums.al4!,
    duration: 203,
    trackNumber: 3,
    discNumber: 1,
    genres: ["Jazz"],
    releaseDate: "2025-01-10",
    coverUrl: mockAlbums.al4!.coverUrl,
    audioUrl: silentUrl,
    popularity: 71,
  },
  {
    id: "t16",
    title: "City Lights",
    artists: [mockArtists.a4!],
    album: mockAlbums.al4!,
    duration: 175,
    trackNumber: 4,
    discNumber: 1,
    genres: ["Lo-Fi"],
    releaseDate: "2025-01-10",
    coverUrl: mockAlbums.al4!.coverUrl,
    audioUrl: silentUrl,
    popularity: 60,
  },
  {
    id: "t17",
    title: "Glacier",
    artists: [mockArtists.a5!],
    album: mockAlbums.al5!,
    duration: 345,
    trackNumber: 1,
    discNumber: 1,
    genres: ["Post-Rock"],
    releaseDate: "2024-09-05",
    coverUrl: mockAlbums.al5!.coverUrl,
    audioUrl: silentUrl,
    popularity: 66,
  },
  {
    id: "t18",
    title: "Summit",
    artists: [mockArtists.a5!],
    album: mockAlbums.al5!,
    duration: 289,
    trackNumber: 2,
    discNumber: 1,
    genres: ["Post-Rock"],
    releaseDate: "2024-09-05",
    coverUrl: mockAlbums.al5!.coverUrl,
    audioUrl: silentUrl,
    popularity: 59,
  },
  {
    id: "t19",
    title: "Tide",
    artists: [mockArtists.a5!],
    album: mockAlbums.al5!,
    duration: 221,
    trackNumber: 3,
    discNumber: 1,
    genres: ["Instrumental"],
    releaseDate: "2024-09-05",
    coverUrl: mockAlbums.al5!.coverUrl,
    audioUrl: silentUrl,
    popularity: 54,
  },
  {
    id: "t20",
    title: "Horizon Line",
    artists: [mockArtists.a5!],
    album: mockAlbums.al5!,
    duration: 198,
    trackNumber: 4,
    discNumber: 1,
    genres: ["Post-Rock", "Instrumental"],
    releaseDate: "2024-09-05",
    coverUrl: mockAlbums.al5!.coverUrl,
    audioUrl: silentUrl,
    popularity: 61,
  },
];
