export const KEYBOARD_SHORTCUTS = {
  PLAY_PAUSE: " ",
  NEXT_TRACK: "ArrowRight",
  PREV_TRACK: "ArrowLeft",
  VOLUME_UP: "ArrowUp",
  VOLUME_DOWN: "ArrowDown",
  MUTE: "m",
  SEEK_FORWARD: "l",
  SEEK_BACKWARD: "j",
  SHUFFLE: "s",
  REPEAT: "r",
  SEARCH: "ctrl+k",
  FOCUS_SEARCH: "/",
  TOGGLE_SIDEBAR: "ctrl+b",
  TOGGLE_QUEUE: "ctrl+q",
  TOGGLE_LYRICS: "ctrl+l",
  TOGGLE_FULLSCREEN: "f",
  ESCAPE: "Escape",
} as const;
